org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.console=plain

minecraft_version=1.21.1
neoforge_version=21.1.222
jei_version=19.25.0.321

mod_id=liquidfuels
mod_name=Liquid Fuels
mod_version=0.2.0
mod_group_id=com.g1739.liquidfuels
mod_authors=交错次元
mod_credits=美术: witzig_heidi(鱼)
mod_license=All Rights Reserved
mod_description=Configuration-driven universal fluid fuel converter.
