org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.console=plain

minecraft_version=1.20.1
forge_version=47.0.3
jei_version=15.2.0.27

mod_id=liquidfuels
mod_name=Liquid Fuels
mod_version=0.1.1
mod_group_id=com.g1739.liquidfuels
mod_authors=交错次元
mod_credits=美术: witzig_heidi(鱼)
mod_license=All Rights Reserved
mod_description=Configuration-driven universal fluid fuel converter.
