pluginManagement {
    repositories {
        maven { url = 'https://maven.minecraftforge.net/' }
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositories {
        maven { url = 'https://maven.minecraftforge.net/' }
        maven { url = 'https://maven.blamejared.com/' }
        mavenCentral()
    }
}

rootProject.name = 'liquidfuels'
